@Url = http://localhost:3000

###

# mostrar todos los vehiculos
GET {{Url}}/vehiculos


###

# mostrar un vehiculo por id
GET {{Url}}/vehiculos/33
 

###

# Crear un nuevo vehiculo
POST {{Url}}/vehiculos
Content-Type: application/json


{
  "marca": "renault",
  "modelo": "clio",
  "patente": "TFT256",
  "ano": 2014,
  "capacidad_carga": 300.00
}

###

# Actualizar un vehiculo 
PUT {{Url}}/vehiculos/2
Content-Type: application/json


{
  "marca": "toyota",
  "modelo": "etios",
  "patente": "AC443DD",
  "ano": 2019,
  "capacidad_carga": 1800.00
}

###

# Eliminar un vehiculo
DELETE {{Url}}/vehiculos/2
